name: "Javier E. Santos"
description: "The Personal Homepage for Javier E. Santos"

url: "https://je-santos.github.io/"

gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

permalink: pretty
highlighter: rouge
markdown: kramdown
kramdown: 
  parse_block_html: true
